[package]
name = "mill-io"
description = "A lightweight event loop library for efficient I/O management"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["event"] }
